### ISSUE TITLE
[Zeitplanung] Erster Meilenstein

### ISSUE THREAD

**Issue by Biggs81** [spochtfreund/mowIT#11]
Vorschlag erster Meilenstein: "Systemanforderungen und Grobentwurf auf Systemebene fertig"? Datum 28.02.19?

**Comment by Joernzie** [comment]
Meinst du nicht dass wir das eine Woche eher schaffen?

**Comment by Biggs81** [comment]
Können wir versuchen.

Also 21.01.19

@spochtfreund was meinst du?

**Comment by Biggs81** [comment]
Meilenstein wie vorgeschlagen angelegt.
