### ISSUE TITLE
[Konventionen] Requirements Issue Format

### ISSUE THREAD

**Issue by Biggs81** [spochtfreund/mowIT#13]
Damit wir nach schon damit arbeiten können, schlage ich vor, dass wir die Requirements issues halbwegs gleich aufbauen. Vorschlag:

Titel: [Requirement] <hier kommt direkt der requirements text hin, unverändert, ungekürzt>

Label: mindestens {requirement}, optional passende Level wie {System} usw.

Optional:
**Rationale**
<Eine Erklärung, warum es das Requirement gibt, weiß man manchmal später nämlich nicht mehr>

Optional
**Quellen**
<Links zu verknüpfen Requirements>, Telko, Dokumente, ...

Man kann wohl auch Issue Templates anlegen, dass kann aber offenbar nur der Owner. @spochtfreund Kannst ja gelegentlich mal ausprobieren, falls du Lust hast.

**Comment by Biggs81** [comment]
Habe #5 so angepasst, wie ich das meine. Ist vielleicht weniger abstrakt.

**Comment by spochtfreund** [comment]
Finde ich super den Vorschlag! So machen wir es. 
Mit dem Template versuche ich mal.

**Comment by spochtfreund** [comment]
Template ist erstellt. Probiert mal aus. Sonst passe ich es noch an...

**Comment by spochtfreund** [comment]
Die Templates liegen im Code-Bereich als .md Datei. Ich denke, da könnt ihr dann darüber auch ändern.... Oder sogar mit CopyNPaste n neues erstellen.... Mal ausprobieren.

**Comment by Joernzie** [comment]
Finde Super so.
