### ISSUE TITLE
Kostenverteilung

### ISSUE THREAD

**Issue by spochtfreund** [spochtfreund/mowIT#2]
~~Hier soll Vorschlag 2 für die Kosten intensiver diskutiert werden. 
Nur zum Test, damit ich die links unter den Issues testen kann. 
Unterticket zu #1~~

[Stefan] Ich hijacke jetzt einfach mal Christians Kommentar und poste die beiden Vorschläge nochmal an dieser Stelle. Sonst verlieren die unten schon gemachten Kommentare ihren Bezug.

### Vorschlag 1

[Stefan] Alle zahlen etwas in einen Topf. Daraus wird eingekauft. Wenn alle wird aufgefüllt.

### Vorschlag 2

[Stefan] Kosten teilen wir so auf wie es "Interessenten" gibt.

Vorraussetzung ist immer, dass das ganze Team mit einer Lösung einverstanden ist.

Beispiel 1: Alle finden Confluence gut. Nur Stefan will gerne damit rumspielen und findet die Kosten angemessen. Stefan muss bezahlen.

Beispiel 2: Elektromotoren finden alle gut, weil unumgänglich :smiley: . Kosten durch drei.

Zu kompliziert?

**Comment by Joernzie** [comment]
Gleichzeitig mit den Kosten musst auch geklärt werden was wir mit dem Prototypen machen.  Ich habe nämlich großes Interesse daran deb Prototyp oder einen Clon möglichst schnell in meinem Garten zu verwenden. Somit bin ich natürlich auch bereit einen größen Teil der Kosten zu tragen. Deshalb ist auch die Modularität so wichtig, damit wir schnell weitere Exemplare bauen können.

**Comment by Joernzie** [comment]
Wenn wir uns sicher sind, dass wir erfolgreich so einen Mäher bauen, bin ich durchaus bereit 500 Euro zu investieren. Plus die Teile die ich schon habe.

**Comment by Biggs81** [comment]
Ich bin natürlich auch daran interessiert, dass das Ding arbeitet ... aber natürlich in meinem Garten 😄!

Das hat mich gerade auf folgende Idee gebracht: Wie wäre es eigentlich wenn wir das ganze von vornherein als eine Art "Umrüstkit" planen. So dass sich jeder seinen Rasenmäher besorgen kann und da die Teile dransteckt. Mit @Joernzie 's fangen wir an. 
Softwareseitig wäre es, denke ich, kein großes Ding. Spurweite und Achsabstand wären halt Parameter, die der Anwender eingeben muss.

**Comment by Biggs81** [comment]
Ich glaube, dass das mit den Tickets gerade durcheinander läuft. Hier wird sinnvoll diskutiert, aber nicht über den "Kosten Vorschlag 2", sondern eher über die Gesamtkosten. 
Und in Ticket #1 sind eigentlich zwei Themen: Einmal "Kostenschätzung/Budget", einmal "Kostenverteilung". 
Oder?

**Comment by Joernzie** [comment]
Also ich hab mal ein weiteres Issue aufgemacht.  Bitte eure Beiträge über die Prototypen dorthin verschieben.

**Comment by Joernzie** [comment]
So und nun zu Kostenvorschlag 2:
Ich finde den Vorschlag genau richtig. Ich meinerseits wäre bereit etwas mehr in die Lidar Sensoren zu investieren weil ich das Prinzip total super finde.

**Comment by Biggs81** [comment]
> 
> 
> Also ich hab mal ein weiteres Issue aufgemacht. Bitte eure Beiträge über die Prototypen dorthin verschieben.

Ich glaube Beiträge lassen sich nicht nachträglich verschieben. Man könnte neu posten, aber dann ist die Reihenfolge wirr

**Comment by Biggs81** [comment]
Also prinzipiell Vorschlag 2? @spochtfreund auch einverstanden? Dann können wir das Ticket schließen.

**Comment by spochtfreund** [comment]
Jo, jeder gibt, wie viel er bereit ist das ein oder andere zu untertützen. Finde ich gut. Bin auch für Vorschlag zwei.
