### ISSUE TITLE
[Requirement] Das System soll Steigungen im Gelände bis zu 15% bewältigen können.

### ISSUE THREAD

**Issue by Biggs81** [spochtfreund/mowIT#20]
**Quellen des Requirements**
https://github.com/spochtfreund/mowIT/wiki/Protokolle#telko-070219

**Comment by Biggs81** [comment]
"Steigung" ist noch nicht definiert.

**Comment by spochtfreund** [comment]
Hier ist eine Übersicht, da sind auch Steigungen gelistet. 
https://www.autonomes-fahren.de/roboter-rasenmaher-vergleich/

**Comment by Biggs81** [comment]
Super, danke für den Link!

Demnach sind also 25 - 45  Prozent Steigung üblich. Krass, hätte ich nicht gedacht.

Glaube in unseren Gärten, haben wir solche Steigungen nicht, oder?

Wollen wir sowas formulieren wie "muss 15 Prozent Steigung, sollte bis zu 45 Grad Steigung"?

**Comment by spochtfreund** [comment]
Da wir auch andere Anforderungen haben, dass das Ganze ein modulares System sein soll, was auf verschiedene Rasenmäher "gesteckt" werden kann, sollten wir dieses hier verwerfen, da wir keinen Einfluss darauf haben. 
Wir können es vielleicht mit dem Prototyp testen, aber es sind bei der weiteren Verwendung zu viele unbekannte.

**Comment by Biggs81** [comment]
Hm? Der Fahrantrieb wird doch auch von uns sein müssen? Dieses Requirement ist dann wichtig für die Auslegung.

**Comment by Biggs81** [comment]
Das hatten wir noch nicht als Requirement. #36 hinzugefügt. Bittebei Bedarf da diskutieren.

**Comment by spochtfreund** [comment]
Höchstens für die Berechnung und einen Beipackzettel, welche Randbedingungen für unser Kit einzuhalten sind. 
Ja und für den Prototyp auch... lassen wir es stehen.

**Comment by Biggs81** [comment]
> Wollen wir sowas formulieren wie "muss 15 Prozent Steigung, sollte bis zu 45 Grad Steigung"?

**Comment by Joernzie** [comment]
15% sollten meiner Meinung nach völlig ausreichen.

**Comment by Biggs81** [comment]
Sehe ich auch so.

**Comment by Biggs81** [comment]
Angepasst
