### ISSUE TITLE
[Requirement] Neigungen des Systems gegenüber der Arbeitsfläche dürfen die Funktionsfähigkeit nicht beeinträchtigen.

### ISSUE THREAD

**Issue by Biggs81** [spochtfreund/mowIT#21]
**Beschreibung des Requirements**
Die Erfassungsebene von Sensoren kann gegenüber der Arbeitsfläche geneigt sein.

**Quellen des Requirements**
https://github.com/spochtfreund/mowIT/wiki/Protokolle#telko-070219
#20 
#22

**Comment by Biggs81** [comment]
"uneben" ist nicht definiert.

**Comment by Joernzie** [comment]
Was haltet ihr von max. Steigung 20%

**Comment by Joernzie** [comment]
Ich würde dieses Requirement löschen.

**Comment by Biggs81** [comment]
Ich find's ganz gut. Als Merker, dass die Sensoren nicht immer ideal parallel zum Untergrund stehen.

**Comment by Joernzie** [comment]
Was hältst du hiervon: 
Das System muss Hindernisse von 3cm Höhe überwinden können.  Eine daraus resultierende Neigung darf das System nicht beeinträchtigen.

**Comment by Biggs81** [comment]
Sehr gut. Zweiten Satz für dieses Requirement übernommen. Ersten Satz für #22 übernommen.
