### ISSUE TITLE
[Requirement] Das System soll sich mit 6 km/h auf der Arbeitsfläche fortbewegen können.

### ISSUE THREAD

**Issue by Biggs81** [spochtfreund/mowIT#31]
**Beschreibung Requirement**
Richtwert: 6-8 km/h

**Quellen des Requirements**
https://github.com/spochtfreund/mowIT/wiki/Protokolle#telko-070219

**Comment by Biggs81** [comment]
6-8 km/h kommt mir sehr zügig vor.

**Comment by Joernzie** [comment]
Wir müssen die maximale Geschwindigkeit ja nicht ausnutzen. Aber es sollte schon möglich sein die 6kmh zu erreichen.

**Comment by Biggs81** [comment]
Okay. Einverstanden.

**Comment by Biggs81** [comment]
Angepasst
