### ISSUE TITLE
[Requirement] Das System soll mulchfähig sein.

### ISSUE THREAD

**Issue by Biggs81** [spochtfreund/mowIT#32]
**Quellen des Requirements**
https://github.com/spochtfreund/mowIT/wiki/Protokolle#telko-070219

**Comment by Biggs81** [comment]
Über #28 kann der passende "Untersatz" beschafft werden. Diese Anforderung kann daher meiner Meinung nach raus.

**Comment by spochtfreund** [comment]
Ja. Bitte raus. Schließen und Tag entfernen, oder wie machen wir das?

**Comment by Biggs81** [comment]
Schließen und "rejected" dran. 

Aber noch auf @Joernzie 's Meinung warten.

**Comment by spochtfreund** [comment]
Ja na klar. War nur meine Meinung.

**Comment by Joernzie** [comment]
Ich stimme auch zu.
