### ISSUE TITLE
[Requirement]  [Requirement] Das System muss so konstruiert sein, dass es problemlos auf der Arbeitsfläche manövrieren kann.

### ISSUE THREAD

**Issue by Biggs81** [spochtfreund/mowIT#33]

**Comment by spochtfreund** [comment]
Wird aus meiner Sicht schwierig mit Abnahmekriterien.

**Comment by Biggs81** [comment]
> Wird aus meiner Sicht schwierig mit Abnahmekriterien.

Vorschlag Testcase: Dauerlauf (wenn alles funzt, einfach mal zwei, drei vier Wochen laufen lassen).

**Comment by Biggs81** [comment]
"dauerhaft problemlos" ist zu unspezifisch. Würde ändern in "darf sich nicht druch Rasenschnitt beeinträchtigen lassen".

**Comment by Biggs81** [comment]
Habe meine Meinung geändert. Sollten wir als Basisrequirement genauso stehen lassen und durch durch weitere Requirements genauer spezifizieren.
