### ISSUE TITLE
[Requirement] Das System soll einen Leistungsschalter ansteuern können, um optional den Antrieb des Mähwerks elektrisch zu starten.

### ISSUE THREAD

**Issue by Biggs81** [spochtfreund/mowIT#34]
**Beschreibung des Requirements**
Das System soll so vorbereitet sein, dass optional ein Relais/Schütz angesteuert werden kann, der den Mähantrieb elektrisch startet (nicht bei Verbrennungsmotoren).

**Quellen des Requirements**
#28

**Comment by Joernzie** [comment]
Ich bin mir nicht sicher ob wir dieses Requirement aufrechterhalten können. Wenn wir ein modulares Umrüstkit entwerfen wollen wird das mit dem anschmeißen des Motors schwierig. Die Unterschiede sind da schon groß und man muss erheblich in den Rasenmäher eingreifen.

**Comment by Biggs81** [comment]
Wollen wir es dann so umformulieren, dass das System selbständig startende Modelle unterstützen soll? Alles was einen Startknopf hat sollte doch gehen (per Relais/Schütz). Akku-Rasenmäher z.B., gibt es Verbrenner mit elektrischem Starter?

**Comment by Joernzie** [comment]
Verbrenner mit E-Start habe ich noch nicht gesehen. Ansonsten können wir das gerne so formulieren.
