### ISSUE TITLE
[Requirement] Auf der Arbeitsfläche sollte möglichst keine Infrastruktur für Sensoren vorgesehen werden.

### ISSUE THREAD

**Issue by Biggs81** [spochtfreund/mowIT#35]
**Beschreibung Requirement**
Beispiel: Reflektormarken sollen nicht auf der Rasenfläche aufgestellt werden müssen.

**Grund für Requirement**
Infrastruktur auf der Rasenfläche reduzieren die Akzeptanz des Systems.
Marker auf der Rasenfläche bleiben potenziell nicht sicher an ihrer Position.

**Quellen des Requirements**
#3

**Comment by Joernzie** [comment]
Ja sehe ich auch so.
