### ISSUE TITLE
[Requirement] Das System darf Infrastruktur für Sensoren vorsehen.

### ISSUE THREAD

**Issue by Biggs81** [spochtfreund/mowIT#38]
**Beschreibung Requirement**
Reflektormarken und dergleichen werden nicht von vornherein ausgeschlossen

**Comment by Joernzie** [comment]
Hmm. Eigentlich bin ich gegen Draht als Begrenzung. Aber als "Spur" um z.B. in den Vorgarten zu kommen ist es sicherlich sehr hilfreich. Also würde ich erst einmal keine Infrastruktur ausschließen.

**Comment by Biggs81** [comment]
Das Requirement zielt in erster Linie auf die Reflektormarken ab.

Bin auf jeden Fall auch gegen Draht. Das ist irgendwie so profan (das sollte aber eigentlich kein Grund sein :smile: )

**Comment by Biggs81** [comment]
Draht im Beispiel gelöscht. Sonst so gelassen.
