### ISSUE TITLE
[Requirement] Das System soll geplante Bahnen abfahren.

### ISSUE THREAD

**Issue by Biggs81** [spochtfreund/mowIT#5]
**Rationale**
Systeme, die zufällige Bahnen abfahren, gibt es schon.

**Comment by Biggs81** [comment]
Dafür.

Systeme, die zufällige Bahnen abfahren, gibt es schon. Entweder als fertiges Produkt zum kaufen und auch als Bastellösung (z.B. https://www.ardumower.de).

**Comment by Joernzie** [comment]
Ja, das autonome fahren von festen Bahnen ist die Basis des Projektes! !

**Comment by spochtfreund** [comment]
Die Bahnen werden berechnet auf Basis eines Algorithmus, nicht vom Benutzer vorgegeben.

**Comment by Joernzie** [comment]
Man Sollte die Bahn aber auch einfach beeinflussen können.  Ich stelle mir eine Software oder App vor, bei der man durch ziehen der Bahnlinien eifach den Track ändern kann.

**Comment by Biggs81** [comment]
> 
> 
> Die Bahnen werden berechnet auf Basis eines Algorithmus, nicht vom Benutzer vorgegeben.



> 
> 
> Man Sollte die Bahn aber auch einfach beeinflussen können. Ich stelle mir eine Software oder App vor, bei der man durch ziehen der Bahnlinien eifach den Track ändern kann.

Das sind separate Anforderungen, bitte in neue Issues posten.

**Comment by Biggs81** [comment]
Habe das jetzt so verstanden, dass wir alle einverstanden mit dieser Anforderung sind (sonst bitte wieder aufmachen).

Diskussion geschlossen und als akzepiert markiert.
