### ISSUE TITLE
[Konventionen] Issues / Label

### ISSUE THREAD

**Issue by Biggs81** [spochtfreund/mowIT#8]
Da die Issues erstmal nur "open" und "closed" sein können, scheint es gängige Praxis zu sein, dass man den Rest, den man so braucht über Labels abbildet.

Ich denke man merkt jetzt schon, dass die Issues sehr schnell sehr viele werden können. Wir sollten also Label machen, über die man sich dann fix Listen zusammenfiltern kann. Zum Beispiel: Die Liste aller abgestimmten Systemanforderungen.

Vorschlag: "open" und "closed" bedeutet für uns 
"open": anschauen und Senf dazu geben
"closed": fertig besprochen
Auf die Weise hat man mit der eingbauten GitHub-Ansicht aller offenen Issues gleich so eine Art ToDo-Liste über alle Ticketkategorien hinweg.

Weitere Meta-Informationen wie "angenommen", "abgelehnt", "gelöst" etc. erfassen wir über separate Label.

Klingt das für euch sinnvoll? (Ich kenne git, aber GitHub ist für mich Neuland).

Würde dann auch mal eine Wiki Seite "Konventionen" anfangen und sowas da festhalten.

**Comment by Joernzie** [comment]
Agree😆

**Comment by Biggs81** [comment]
Angenommen in Telko 07.02.19
